namespace Monolith.Services;

public sealed record SynthesizedAgent(string Id, string Name, string StrategyPrompt, string GeneratedCSharpCode, string Status, DateTimeOffset CreatedAtUtc);

public sealed class AiAgentSynthesizerService
{
    private readonly List<SynthesizedAgent> _agents = [];

    public List<SynthesizedAgent> GetAgents() => _agents;

    public SynthesizedAgent SynthesizeAgent(string name, string scenarioPrompt)
    {
        string csharpCode = "\n// Autogenerated AI Trading Agent: " + name +
            "\n// Strategy Scenario: " + scenarioPrompt +
            "\npublic sealed class DynamicAgent \n{\n    public void EvaluateMarket(decimal bid, decimal ask, decimal volume)\n    {\n        decimal spread = ask - bid;\n        if (spread > 0.05m && volume > 1000m)\n        {\n            System.Console.WriteLine(\"[AI Agent " + name + "] Executing trade trigger\");\n        }\n    }\n}";

        var agent = new SynthesizedAgent(
            Guid.NewGuid().ToString("N")[..8],
            name,
            scenarioPrompt,
            csharpCode,
            "Active & Deployed",
            DateTimeOffset.UtcNow
        );

        _agents.Insert(0, agent);
        return agent;
    }
}
