<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Monolith.Telemetry</RootNamespace>
    <AssemblyName>Monolith.Telemetry</AssemblyName>
  </PropertyGroup>
</Project>
