<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Monolith.Sentinel</AssemblyName>
    <RootNamespace>Monolith.Sentinel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monolith.Shared\Monolith.Shared.csproj" />
  </ItemGroup>
</Project>
